export const CREATE_BOOK = 'CREATE_BOOK'
export const GET_BOOK_BY_ID = 'GET_BOOK_BY_ID'
export const MODIFY_BOOKS_LIST = 'MODIFY_BOOKS_LIST'
export const FETCH_BOOKS = 'FETCH_BOOKS'
export const CONTINUE_LIST = 'CONTINUE_LIST'
export const SET_PAGE_TYPE = 'SET_PAGE_TYPE'

export const TO_PAGE_EDIT_BOOK = 'TO_PAGE_EDIT_BOOK'
export const EDIT_BOOK = 'EDIT_BOOK'
export const DELETE_BOOK = 'DELETE_BOOK'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'

export const CREATE_PLACE = 'CREATE_PLACE'
export const DELETE_PLACE = 'DELETE_PLACE'
export const SAVE_PLACE_CODE = 'SAVE_PLACE_CODE'
export const SAVE_BOOK_ID = 'SAVE_BOOK_ID'

export const RESET_FILTER_SETTINGS = 'RESET_FILTER_SETTINGS'
export const SAVE_SORT_VALUE = 'SAVE_SORT_VALUE'
export const SAVE_FILTER_VALUE = 'SAVE_FILTER_VALUE'
export const SAVE_SEARCH_VALUE = 'SAVE_SEARCH_VALUE'
export const SAVE_SEARCH_FIELD_VALUE = 'SAVE_SEARCH_FIELD_VALUE'

export const CHANGE_LOCALE = 'CHANGE_LOCALE'
export const REGISTER = 'REGISTER'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SET_ERROR = 'SET_ERROR'

export const TOKEN_TRUE = 'TOKEN_TRUE'
export const TOKEN_FALSE = 'TOKEN_FALSE'